spring.application.name=home
# Profil par defaut
spring.profiles.default=dev

# JPA/Hibernatep$
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuration de transaction pour éviter read-only
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.open-in-view=false
spring.transaction.default-timeout=30

# Configuration Jackson pour Hibernate
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null



#spring modulith
spring.modulith.detection-strategy=explicitly-annotated

# Configuration Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.display-operation-id=true
springdoc.packages-to-scan=home
springdoc.paths-to-match=/api/**
springdoc.show-actuator=true
